<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [c++-pthreads] cancellation points report failure
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20cancellation%20points%20report%20failure&In-Reply-To=%3C20031220045618.GA27836%40tofu.dreamhost.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000019.html">
   <LINK REL="Next"  HREF="000022.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[c++-pthreads] cancellation points report failure</H1>
    <B>Nathan Myers</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20cancellation%20points%20report%20failure&In-Reply-To=%3C20031220045618.GA27836%40tofu.dreamhost.com%3E"
       TITLE="[c++-pthreads] cancellation points report failure">ncm at cantrip.org
       </A><BR>
    <I>Sat Dec 20 04:56:18 UTC 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="000019.html">[c++-pthreads] cancellation points report failure
</A></li>
        <LI>Next message: <A HREF="000022.html">[c++-pthreads] cancellation points report failure
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#21">[ date ]</a>
              <a href="thread.html#21">[ thread ]</a>
              <a href="subject.html#21">[ subject ]</a>
              <a href="author.html#21">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Fri, Dec 19, 2003 at 08:15:03PM -0500, David Abrahams wrote:
&gt;<i> Ted Baker &lt;<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">baker at cs.fsu.edu</A>&gt; writes:
</I>&gt;<i> &gt; How are you going to implement this version of
</I>&gt;<i> &gt; read() that raises the exeption?
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; The only way I know is to create a wrapper for the C-language
</I>&gt;<i> &gt; read() function (or the corresponding system call trap), check the
</I>&gt;<i> &gt; return value and if it is negative, throw the exception.
</I>&gt;<i> 
</I>&gt;<i> IIUC, you're still being confused in the same way... but I'll let
</I>&gt;<i> Nathan explain himself because, who knows, maybe it's me that's
</I>&gt;<i> confused after all? 
</I>
As I had described the goal, ::read() would never throw an exception.
Library code would never expect, or be prepared to handle, an exception 
from it.  Instead, it would return -1.  It would set errno to EIO or 
ECANCELED or ESOMEDAMNTHINGELSE defined by POSIX.

The simplest way to make this happen would be for the C library to 
do it.  I'm most interested now in discovering and defining semantics 
for synchronous cancellation that make it usable with C++ libraries.  
If we fail, then we are back to the status quo, which is that thread 
cancellation is incompatible with C++ libraries.

Since it apparently isn't yet clear to everybody what I had suggested,
I'll outline it again:

  C library and system calls never throw.
  In the event of cancellation, cancellation point functions report 
    failure via their normal means (e.g. return -1, or NULL), and set 
    errno if appropriate.  Blocked calls fail immediately.
  C++ library functions that are normally allowed to throw may throw
    a cancellation exception.  (E.g. std::filebuf::overflow().)
  A thread, once cancelled, stays cancelled, regardless of any C++ 
    catch blocks entered or left.
  C++ catch blocks work normally; a cancellation exception may be
    rethrown, or swallowed like any other. 
  In a catch block handling a cancellation exception, functions
    identified as cancellation points work normally.
  When a cancellation exception is swallowed by a catch block, 
    subsequently-called cancellation point functions report failure, 
    as before, until another cancellation exception is thrown.
  Eventually the inability of the thread to achieve anything leads it
    to top-level code equipped to recognize the cancelled condition as 
    such, and to clean up and die in a controlled way.

I am certain that with enough control over the execution environment,
the above is more or less trivially implementable.

A simpler model would have calling cancellation-point functions from
within a catch block also fail or throw, and the caller be expected
to tolerate the failure or catch (and discard or rethrow) any 
resulting exception.

Nathan Myers
<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">ncm at cantrip.org</A>

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000019.html">[c++-pthreads] cancellation points report failure
</A></li>
	<LI>Next message: <A HREF="000022.html">[c++-pthreads] cancellation points report failure
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#21">[ date ]</a>
              <a href="thread.html#21">[ thread ]</a>
              <a href="subject.html#21">[ subject ]</a>
              <a href="author.html#21">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
