<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> pthread_cancel and EH: let's try this again
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3Cull4d2cze.fsf%40boost-consulting.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000327.html">
   <LINK REL="Next"  HREF="000328.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>pthread_cancel and EH: let's try this again</H1>
    <B>David Abrahams</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3Cull4d2cze.fsf%40boost-consulting.com%3E"
       TITLE="pthread_cancel and EH: let's try this again">dave at boost-consulting.com
       </A><BR>
    <I>Mon Jul 11 22:29:25 UTC 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="000327.html">[c++-pthreads] pthread_cancel and EH: let's try this again
</A></li>
        <LI>Next message: <A HREF="000328.html">[c++-pthreads] pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#329">[ date ]</a>
              <a href="thread.html#329">[ thread ]</a>
              <a href="subject.html#329">[ subject ]</a>
              <a href="author.html#329">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Mark Mitchell &lt;<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">mark at codesourcery.com</A>&gt; writes:

&gt;<i> Jason Merrill wrote:
</I>&gt;&gt;<i> Previous discussion on this topic ended in something of a stalemate.
</I>&gt;<i>
</I>&gt;<i> Thank you for re-starting the discussion.  I wasn't happy with the 
</I>&gt;<i> stalemate, but I didn't have the fortitude to try again!
</I>&gt;<i>
</I>&gt;&gt;<i> In previous discussions, my favored solution was:
</I>&gt;&gt;<i> 1a) Cancellation is disabled during stack unwinding, to avoid trying to
</I>&gt;&gt;<i> throw out of a destructor.
</I>&gt;&gt;<i> 1b) Make cancellation a normal exception that can be caught and discarded,
</I>&gt;&gt;<i> but have the destructor for the exception re-assert cancellation so that
</I>&gt;&gt;<i> the process will begin again at the next cancellation point.
</I>&gt;<i>
</I>&gt;<i> I think this is a reasonable solution.
</I>&gt;<i>
</I>&gt;<i> I think I'd still prefer just to have the handler catch the exception 
</I>&gt;<i> and discard it, 
</I>
Me too.  I don't see any need to make this exception special.

&gt;<i> but not strongly enough to try to stand in the way of progress.
</I>
Me too.  I haven't thought through the arguments about whether this
re-cancel behavior is a good idea.  In fact, I don't know what they
are, so if someone could summarize that would be great.

&gt;<i> If you can build consensus around this option, I'll support 
</I>&gt;<i> it fully.
</I>&gt;<i>
</I>&gt;<i> Both your model, and the variant I suggest, preserve the pleasant 
</I>&gt;<i> property that code which already handles &quot;random&quot; exceptions (like that 
</I>&gt;<i> in libraries designed to plug into applications) continues to behave 
</I>&gt;<i> reasonably well in the presence of cancellation.
</I>
Yep, that's important to me.

&gt;<i> Code that doesn't handle random exceptions probably doesn't handle 
</I>&gt;<i> thread-cancellation either; if it's relying on certain functions 
</I>&gt;<i> throwing only certain exceptions, then it's probably written to work in 
</I>&gt;<i> a relatively controlled environment.  (Of course, if it were compiled 
</I>&gt;<i> with headers that say that cancellation point functions throw no 
</I>&gt;<i> exceptions, then it would be completely hosed, under any of these models.)
</I>
Unless the code doesn't call any of those cancellation point
functions.

&gt;&gt;<i> Then there's the Ada-equivalent model:
</I>&gt;&gt;<i> 2a) Cancellation is disabled during destructors and empty exception specs.
</I>&gt;&gt;<i> 2b) Cancellation exceptions are not caught by (...).
</I>&gt;<i>
</I>&gt;<i> I think this ought to be considered a non-starter.  Ignoring &quot;catch 
</I>&gt;<i> (...)&quot; blocks in C++ is worse than just killing the thread.  Style 
</I>&gt;<i> considerations aside, there's a ton of code that relies on that to clean 
</I>&gt;<i> up resources, or to otherwise restore state; and running destructors 
</I>&gt;<i> after skipping &quot;catch (...)&quot; blocks is just plain wrong, in my opinion.
</I>
Agree.

&gt;<i> Maybe in workstation/server applications this makes sense to some 
</I>&gt;<i> people, but I don't think it makes any sense at all on an embedded 
</I>&gt;<i> system, where the system is often set up to handle complete process 
</I>&gt;<i> death, but not weird inconsistencies.  You'd be breaking people's 
</I>&gt;<i> program verification regimes, as well.
</I>
The platform doesn't matter.  Destructors have to be able to rely on
program invariants being maintained, and as you imply, skipping a
catch(...) block in the middle of unwinding is likely to break those
invariants.

&gt;&gt;<i> Thread robustness (catch and retry).  A thread could have a catch (...)
</I>&gt;&gt;<i>   at the top level to try to recover from errors, on the principle that
</I>&gt;&gt;<i>   limping along is better than total failure.  Previous discussion seemed
</I>&gt;&gt;<i>   to assume that the users would want this to catch cancellation as well,
</I>&gt;&gt;<i>   but I think that's wrong; if someone specifically told the thread to go
</I>&gt;&gt;<i>   away, they don't want it to recover, they want it to go away.  
</I>&gt;<i>
</I>&gt;<i> I agree.  In fact, despite my oft-stated opinion that it should be 
</I>&gt;<i> possible to catch cancellation exceptions, I agree that actually doing 
</I>&gt;<i> that -- and never restarting the cancellation process -- would generally 
</I>&gt;<i> be a bug in user code.
</I>
Almost.  If the thread (optionally issues some kind of report and)
exits -- an entirely plausible response to an exception ending up in
catch(...)  because you didn't recognize it -- I think that's not
quite bad enough to be a bug, and technically it does not amount to
restarting the cancellation process.  That would entail re-throwing a
cancellation exception IMO.

&gt;<i> The reason I'm OK with catching the exception is to do things like:
</I>&gt;<i>
</I>&gt;<i>   try { ... } catch (Cancellation) {
</I>&gt;<i>     cancelled = 1;
</I>&gt;<i>   }
</I>&gt;<i>   /* Other stuff here.  We have no finally clauses in C++.  */
</I>&gt;<i>   if (cancelled) {
</I>&gt;<i>     throw Cancellation;  // Or, maybe a different exception type, that
</I>&gt;<i>                          // tells the top level to cancel the thread.
</I>&gt;<i>   }
</I>
As Peter D. suggested, something similar happens when C++
interoperates with Python (and I'm sure many other systems written in
'C').  Usually &quot;Other stuff here&quot; is actually a few stack frames of
'C' code.

&gt;<i> Your auto-recancel semantics are probably good enough in this kind of 
</I>&gt;<i> situation.
</I>
I'd like more detail on how it helps (and of course any arguments
against it too).

&gt;&gt;<i> Ulrich Drepper insists that #1 is impossible, because pthread cancellation
</I>&gt;&gt;<i> is an irreversible state change.  But I'm not sure why you can't just flip
</I>&gt;&gt;<i> various flags back to where they were before.
</I>
Agree.

&gt;<i> Yes, I've asked Ulrich about this several times, and have never gotten 
</I>&gt;<i> an explanation.
</I>&gt;<i>
</I>&gt;&gt;<i> My current inclination is to go with model #2; backwards compatibility
</I>&gt;&gt;<i> with code written to work with pthread_cleanup_push/pop seems like a
</I>&gt;&gt;<i> powerful argument in its favor.  People who want model #1 can use a
</I>&gt;&gt;<i> different threading library, such as Boost.Threads.
</I>&gt;<i>
</I>&gt;<i> Oh, no...  I thought up until this paragraph that we were going to be on 
</I>&gt;<i> the same page.
</I>
Whoa! Me too!

&gt;<i> I think that if #1 really is impossible, #2 might be second-best.  But, 
</I>&gt;<i> I'd very much like an explanation of why #1 is impossible.  While I have 
</I>&gt;<i> very high confidence in Ulrich's technical abilities, I don't think we 
</I>&gt;<i> should have to take his opinions on faith.
</I>
Yah.  Number 2 breaks too many programs and libraries that ought to be
correct in the presence of threads.  

-- 
Dave Abrahams
Boost Consulting
www.boost-consulting.com


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000327.html">[c++-pthreads] pthread_cancel and EH: let's try this again
</A></li>
	<LI>Next message: <A HREF="000328.html">[c++-pthreads] pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#329">[ date ]</a>
              <a href="thread.html#329">[ thread ]</a>
              <a href="subject.html#329">[ subject ]</a>
              <a href="author.html#329">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
