From stefan at codesourcery.com  Mon Oct  1 15:02:12 2007
From: stefan at codesourcery.com (Stefan Seefeld)
Date: Mon, 01 Oct 2007 11:02:12 -0400
Subject: QMTest 2.4 released
Message-ID: <47010BF4.9050700@codesourcery.com>

I'm pleased to announce the QMTest 2.4 release, available
for download from http://www.codesourcery.com/qmtest/2.4/download.html.

This release contains a number of major improvements
relative to QMTest 2.3, notably:


*  A new "expectation_database" extension kind has been added, with two
   built-in implementations, previous_testrun.PreviousTestRun, and
   xml_expectation_database.XMLExpectationDatabase. The command-line
   interface has been enhanced to support this.

*  A new CompilationTestDatabase has been added, and various related
   test classes and utility functions have been improved to support it.

*  The QMTest documentation has been much improved. The tutorial has been
   restructured to contain three chapters:
   1) concepts, 2) customization, 3) extension.

*  Changes have been made to make QMTest work with Python 2.5.

*  QMTest now installs its data into <prefix>/share/qmtest, and its
   documentation into <prefix>/share/doc/qmtest.



-- 
Stefan Seefeld
CodeSourcery
stefan at codesourcery.com
(650) 331-3385 x718


From chamont at llr.in2p3.fr  Tue Oct 16 14:53:22 2007
From: chamont at llr.in2p3.fr (David Chamont)
Date: Tue, 16 Oct 2007 16:53:22 +0200
Subject: Problems with first steps
Message-ID: <1faa9efb0710160753t15b1ac50g26628248f08156d9@mail.gmail.com>

Hi,

I am a new user, so I apologize for the dummy questions, or the
feature request which will certainly not take into account the
history of the product. My single source of knowledge till now
is the 2.4 user guide.

I am trying to set up a first test suite.
My application is compiled with an external product which is
preparing a makefile, and then I type "make".
I tried to declare the compilation step as a resource :

     qmtest create -i myProg -a 'command="cd ../build && make"'
          resource command.ShellCommandTest

Unhappily, Qmtest does not accept a command.ShellCommandTest as
a resource. The user guide let me think that perhaps it would work,
and I would have liked, because the provided resources are quite limited
to basic compilation process.

Well, I then tried to declare my "make" command as a "test", which I
planned to declare as a prerequisite to the further execution tests :

     qmtest create -i myProg -a 'command="cd ../build && make"'
          test command.ShellCommandTest

Now, my problem is that this newly created test seems to
be invisible to qmtest. Qmtest does not list it, althought it is listing
correctly the fake python tests I have declared before.
The output of "qmtest ls -lr" :

     directory                 dir1
     test      python.ExecTest dir1.one
     test      python.ExecTest dir1.two
     directory                 dir2
     directory                 dir2.dir3
     test      python.ExecTest dir2.dir3.one
     test      python.ExecTest dir2.dir3.two
     test      python.ExecTest dir2.one
     test      python.ExecTest python_fail
     test      python.ExecTest python_pass

The ouput of "ls" :

     myProg.qmt
     dir1.qms
     dir2.qms
     python_fail.qmt
     python_pass.qmt
     QMTest
     results.qmr

Any idea ?

A detail : for consistency, "qmtest ls ." should work, just the same
as "qmtest run .", no ?

Cheers.
David.

-- 
David Chamont
(33)1.69.33.56.33
LLR - IN2P3 - CNRS - Ecole Polytechnique


From edgar.johansen at kongsberg.com  Tue Oct 23 10:51:26 2007
From: edgar.johansen at kongsberg.com (Edgar Johansen)
Date: Tue, 23 Oct 2007 12:51:26 +0200
Subject: Bug report: Garbled path on MS Windows XP
Message-ID: <OF38108F51.E853FB82-ONC125737D.003A659A-C125737D.003B4006@km.kongsberg.com>

I installed QMTest v. 2.4 on Windows XP with Python v. 2.5.

The result of running qmtest.py was:
C:\prog\spdev\swlib\C-Test\osif\tdb>qmtest.py gui
Traceback (most recent call last):
  File "C:\app\Python25\Scripts\qmtest.py", line 126, in <module>
    qm.diagnostic.load_messages("test")
  File "C:\app\Python25\Lib\site-packages\qm\diagnostic.py", line 204, in 
load_messages
    get_diagnostic_set().ReadFromFile(diagnostic_file)
  File "C:\app\Python25\Lib\site-packages\qm\diagnostic.py", line 154, in 
get_diagnostic_set
    "common.txt"))
  File "C:\app\Python25\Lib\site-packages\qm\diagnostic.py", line 83, in 
ReadFromFile
    file = open(path, "r")
IOError: [Errno 2] No such file or directory: 
'C:\x07pp\\Python25\\share/qmtest\\diagnostics\\common.txt'

This seems to happen when the path to the Python installation contains an 
element starting with a lowercase letter in the range a-f. In this case, 
the path is C:\app\Python25

The contents of the config.py file was:
version='2.4'
data_dir='share/qmtest'
doc_dir='share/doc/qmtest'
# The following variables are set / adjusted during
# the build / install process.
extension_path='share\qmtest\site-extensions-2.5'
prefix='C:\app\Python25'

As a workaround, I modified the prefix definition in config.py:
version='2.4'
data_dir='share/qmtest'
doc_dir='share/doc/qmtest'
# The following variables are set / adjusted during
# the build / install process.
extension_path='share\qmtest\site-extensions-2.5'
prefix='C:/app/Python25'
--
Edgar Johansen
Kongsberg Seatex AS


