<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [c++-pthreads] What are the real issues?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20What%20are%20the%20real%20issues%3F&In-Reply-To=%3C20040107213346.GC2884%40diablo.name%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000107.html">
   <LINK REL="Next"  HREF="000110.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[c++-pthreads] What are the real issues?</H1>
    <B>Ted Baker</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20What%20are%20the%20real%20issues%3F&In-Reply-To=%3C20040107213346.GC2884%40diablo.name%3E"
       TITLE="[c++-pthreads] What are the real issues?">baker at cs.fsu.edu
       </A><BR>
    <I>Wed Jan  7 21:33:46 UTC 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="000107.html">[c++-pthreads] What are the real issues?
</A></li>
        <LI>Next message: <A HREF="000110.html">[c++-pthreads] What are the real issues?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#137">[ date ]</a>
              <a href="thread.html#137">[ thread ]</a>
              <a href="subject.html#137">[ subject ]</a>
              <a href="author.html#137">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;<i>   In a catch block handling a cancellation exception, functions
</I>&gt;<i>     identified as cancellation points work normally.
</I>
Do you mean to imply that the implementation of each of these functions
looks to see whether the call is coming from inside a catch block?
(It seems you are asking the behavior of these calls to vary,
depending on the context of the call, working normally in a
catch block but failing outside.)

&gt;<i>   Eventually the inability of the thread to achieve anything leads it
</I>&gt;<i>     to top-level code equipped to recognize the cancelled condition as 
</I>&gt;<i>     such, and to clean up and die in a controlled way.
</I>
This assumes the code has been structured with cancellation in 
mind, so that control passes upward in the way you expect, or
that you are lucky.

--Ted

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000107.html">[c++-pthreads] What are the real issues?
</A></li>
	<LI>Next message: <A HREF="000110.html">[c++-pthreads] What are the real issues?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#137">[ date ]</a>
              <a href="thread.html#137">[ thread ]</a>
              <a href="subject.html#137">[ subject ]</a>
              <a href="author.html#137">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
